# Generated by Django 4.1.2 on 2022-10-19 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='product',
            name='product_image',
            field=models.ImageField(default='product_images/Product-Image-Coming-Soon.jpg', upload_to='product_images/'),
        ),
    ]
