# Generated by Django 4.1.2 on 2022-11-15 12:24

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_category_options_alter_product_product_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductImageGalley',
            fields=[
                ('images', models.ImageField(upload_to='product_images/')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product')),
            ],
        ),
    ]
