# Generated by Django 4.1.2 on 2022-11-15 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_productimagegalley'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImageGalley',
            new_name='ProductImageGallery',
        ),
    ]
